apiVersion: v1
kind: Pod
metadata:
    annotations: {}
    labels: {}
    name: pod
    namespace: default
spec:
    containers:
        - image: nginx
          image Pull Policy: Always
          name: ""
---
apiVersion: v1
kind: Service
metadata:
    annotations: {}
    labels: {}
    name: service
    namespace: default
spec:
    ports:
        - name: target-port
          port: 80
          protocol: TCP
          target Port: 8080
        - port: 80
          protocol: TCP
---
apiVersion: v1
kind: Namespace
metadata:
    annotations: {}
    labels: {}
    name: default
    namespace: default
